### ISSUE TITLE
Issues with append_dist_to_stop_times for New York MTA data

### ISSUE THREAD

**Issue by moshobo** [mrcagney/gtfs_kit#21]
Hello,

I've been using gtfs_kit for a while on a number of GTFS feeds, and I always seem to have issues with New York's MTA GTFS feed ([zip file](http://web.mta.info/developers/data/nyct/subway/google_transit.zip)).

Specifically, the issue seems to be when using `append_dist_to_stop_times` function from `stop_times.py`. I seem to be running into a problem with the shapes coming from the GTFS file.

Here's an example of the code:
```
import gtfs_kit as gk

path = "http://web.mta.info/developers/data/nyct/subway/google_transit.zip" # NY MTA
feed = gk.read_feed(path, dist_units='mi')
moving_feed = feed.append_dist_to_stop_times()
```

And this is the resulting error:
```
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    moving_feed = feed.append_dist_to_stop_times()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gtfs_kit/stop_times.py", line 114, in append_dist_to_stop_times
    .apply(compute_dist)
     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1824, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1885, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 918, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gtfs_kit/stop_times.py", line 65, in compute_dist
    linestring = geom_by_shape[shape]
                 ~~~~~~~~~~~~~^^^^^^^
KeyError: nan
```

It seems that the `shape` as defined in `shape = g.shape_id.iat[0]` is a float that is `nan`, causing things to break. I was able to make a temporary workaround by looking at the `shape` and returning `None` if it was nan.

Workaround:
```
g = group.copy()

# Compute the distances of the stops along this trip and memoize.
shape = g.shape_id.iat[0]
if type(shape) == float and np.isnan(shape):
    return None 
```

I thought it would be good to bring up two things for discussion:
1. Should the `append_dist_to_stop_times` function also look for nan shapes and skip them?
2. Is this a problem with the MTA's GTFS feed? If so, what file(s) should I be looking at for causes of this issue? Shapes.txt?

If you've made it this far, I appreciate you taking the time to read it, and I'm greatful for all the work of gtfs_kit!

**Comment by diegoperezalvarez** [comment]
Hi @moshobo,

Looking at the feed you linked, I see that the `trips` subfile contains some trips with empty (`NaN`) references to `shape_id`. Also, passing the feed through a gtfs validator online does throw up a few warnings which you may [want to look into](
https://gtfs-validator-results.mobilitydata.org/7da8ae08-974a-49ce-85ab-117ec6ce6c4f/report.html). This is par for the course when working with GTFS.

Judging by this, I would say this represents expected behaviour from `append_dist_to_stop_times` and to avoid it, I would remove the routes which do not have shapes (through `restrict_to_routes`) - I suspect these are ferry routes, but I can't be 100% sure.

If anything, I think a better change would be to simply throw a more descriptive error message if any `NaN`s are found in `trips` under `shape_id`, just after [the check for whether the `shapes` subfile exists](https://github.com/mrcagney/gtfs_kit/blob/0b95c49e1b8f8e50f5a84023ac21c598d13dc8d3/gtfs_kit/stop_times.py#L55).

**Comment by araichev** [comment]
Thanks for the bug report @moshobo .
I've now tweaked `stop_times.append_dist_to_stop_times` to handle trips missing shapes by setting their distances to NaN.
The following code now returns `True`.
```
path = "http://web.mta.info/developers/data/nyct/subway/google_transit.zip"
feed = gk.read_feed(path, dist_units='mi')
shapeless_trips = feed.trips.loc[lambda x: x["shape_id"].isna(), "trip_id"].unique()
feed2 = feed.append_dist_to_stop_times()
assert feed2.stop_times.loc[lambda x: x["trip_id"].isin(shapeless_trips), "shape_dist_traveled"].isna().all()
```

This change is in the latest `develop` branch, and i'll make a new release with it soon after reviewing the repo's other open issues.
